id = "gameobject2"

[transform]
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0]
scale = [1.0, 1.0, 1.0]

[mesh]
path = "/home/malkaviel/Documents/projects/intellij/maskerad_level_parser/resource_test/untitled.gltf"